// Listado de productos - generado desde Listado_productos_Stock.xlsx
// Pestañas usadas: Productos terminados, Pasteleria, VARIOS
// Total productos: 371  |  Códigos autogenerados (90001+): 127
//
// price1 = precio de venta en Madrid y Málaga · price2 = precio de venta en BCN
// Cargados desde "listas_de_precios_terminados_-_MP_-_varios.xlsx" cruzando por
// NOMBRE de producto (los códigos de esa lista de precios no coinciden con los
// códigos de este archivo, son dos sistemas distintos). Los que quedaron en
// null son productos que no se encontraron con nombre exacto en esa lista
// (sobre todo insumos internos: uniformes, limpieza, moldes, materias primas)
// o que sí necesitan precio pero el nombre está escrito distinto en cada lado
// -- esos se completan a mano desde la pantalla de Precios de batodesrets.
const PRODUCTS = [
  { code: 2015, name: 'MASCARPONE CON FRUTOS ROJOS', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 3.4845, price1: null, price2: null },
  { code: 2006, name: 'COOKIES & CREAM', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 3.4085, price1: 1.017, price2: 0.251 },
  { code: 2001, name: 'CHEESECAKE DE MARACUYA', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 4.1745, price1: 0.972, price2: 0.66 },
  { code: 2357, name: 'CHEESECAKE DE PISTACCHIO', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 4.24, price1: null, price2: null },
  { code: 2020, name: 'STRACCIATELLA', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 3.433, price1: null, price2: null },
  { code: 2003, name: 'CHOCOLATE BLANCO & PISTACCHIO CROCK', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 3.5505, price1: 7.053, price2: 3.868 },
  { code: 2311, name: 'VAINILLA', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 3.2765, price1: 4.848, price2: 2.273 },
  { code: 2022, name: 'TIRAMISU', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 3.3245, price1: 5.142, price2: 2.56 },
  { code: 2407, name: 'TIRAMISU AL PISTACHO', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 4.5186, price1: null, price2: null },
  { code: 2011, name: 'KING BUENO', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 3.7375, price1: 6.433, price2: 5.242 },
  { code: 2312, name: 'GIANDUIA BLANCA & CARAMELO SALADO', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 4.013, price1: null, price2: null },
  { code: 2017, name: 'PEANUT CARAMEL', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 4.0375, price1: 6.339, price2: 3.891 },
  { code: 2370, name: 'PRETZEL', category: 'HELADO (KG)', unit: 'Kg', avgWeight: null, price1: 6.546, price2: 3.606 },
  { code: 2016, name: 'NOCCIOLA SUPREMA', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 3.795, price1: 8.886, price2: 6.255 },
  { code: 2018, name: 'PISTACCHIO SICILIA', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 3.629, price1: 1.308, price2: 0.675 },
  { code: 2211, name: 'SAMBAYON', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 3.953, price1: 7.496, price2: 5.32 },
  { code: 2007, name: 'DULCE DE LECHE CON DDL', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 3.7, price1: null, price2: null },
  { code: 2142, name: 'DULCE DE LECHE GRANIZADO', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 3.6525, price1: 6.157, price2: 3.235 },
  { code: 2004, name: 'CHOCOLATE LUCCIANO\'S C BOMBON DE AVELLANAS', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 3.545, price1: null, price2: null },
  { code: 2381, name: 'CHOCOLATE DUBAI', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 4.1035, price1: 9.355, price2: 6.369 },
  { code: 2010, name: 'GIANDUIOTTO', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 4.088, price1: 6.586, price2: 4.08 },
  { code: 2019, name: 'SORBETE SUPREMO 80%', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 4.2195, price1: 1.248, price2: 0.501 },
  { code: 2143, name: 'BANANA SPLIT', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 3.9975, price1: 5.107, price2: 2.596 },
  { code: 2012, name: 'LEMON PIE', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 3.9905, price1: 5.916, price2: 3.304 },
  { code: 2005, name: 'COCCO ROCK', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 3.6115, price1: null, price2: null },
  { code: 2013, name: 'LIMA', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 3.6605, price1: 6.098, price2: 3.37 },
  { code: 2014, name: 'MANGO', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 4.1525, price1: 1.011, price2: 0.22 },
  { code: 2008, name: 'FRESA', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 3.214, price1: 0.98, price2: 0.285 },
  { code: 2009, name: 'MARACUYA', category: 'HELADO (KG)', unit: 'Kg', avgWeight: 3.331, price1: 1.023, price2: 0.223 },
  { code: 90128, name: 'VARIOS HELADO', category: 'HELADO (KG)', unit: 'Kg', avgWeight: null, price1: null, price2: null },
  { code: 2205, name: 'FRESA', category: 'ICE POPS CLASSIC', unit: 'Unidad', avgWeight: null, price1: 0.98, price2: 0.285 },
  { code: 2206, name: 'LIMON', category: 'ICE POPS CLASSIC', unit: 'Unidad', avgWeight: null, price1: 0.983, price2: 0.181 },
  { code: 2204, name: 'MANGO', category: 'ICE POPS CLASSIC', unit: 'Unidad', avgWeight: null, price1: 1.011, price2: 0.22 },
  { code: 2207, name: 'MARACUYA', category: 'ICE POPS CLASSIC', unit: 'Unidad', avgWeight: null, price1: 1.023, price2: 0.223 },
  { code: 2028, name: 'MASCARPONE CON FRUTTI DI BOSCO', category: 'ICE POPS SIN BAÑO', unit: 'Unidad', avgWeight: null, price1: 1.116, price2: 0.316 },
  { code: 2027, name: 'KING NERO', category: 'ICE POPS SIN BAÑO', unit: 'Unidad', avgWeight: null, price1: 1.142, price2: 0.352 },
  { code: 2026, name: 'FRESA Y CHANTILLY', category: 'ICE POPS SIN BAÑO', unit: 'Unidad', avgWeight: null, price1: 1.007, price2: 0.263 },
  { code: 2025, name: 'COOKIES & CREAM', category: 'ICE POPS SIN BAÑO', unit: 'Unidad', avgWeight: null, price1: 1.017, price2: 0.251 },
  { code: 2208, name: 'PISTACHO SIN AZUCAR', category: 'ICE POPS SIN BAÑO', unit: 'Unidad', avgWeight: null, price1: 1.29, price2: 0.471 },
  { code: 2035, name: 'OLI KING', category: 'ICE POPS BAÑADOS', unit: 'Unidad', avgWeight: null, price1: 1.399, price2: 0.435 },
  { code: 2033, name: 'FIORE', category: 'ICE POPS BAÑADOS', unit: 'Unidad', avgWeight: null, price1: 1.357, price2: 0.621 },
  { code: 2029, name: 'CHANTILLY CROCANTE', category: 'ICE POPS BAÑADOS', unit: 'Unidad', avgWeight: null, price1: 1.417, price2: 0.469 },
  { code: 2032, name: 'DULCE DE LECHE CROCANTE', category: 'ICE POPS BAÑADOS', unit: 'Unidad', avgWeight: null, price1: 1.395, price2: 0.391 },
  { code: 2031, name: 'CHOCOLATE CROCANTE', category: 'ICE POPS BAÑADOS', unit: 'Unidad', avgWeight: null, price1: 1.358, price2: 0.38 },
  { code: 2034, name: 'NOCCIOLA CROCANTE', category: 'ICE POPS BAÑADOS', unit: 'Unidad', avgWeight: null, price1: 1.493, price2: 0.462 },
  { code: 2030, name: 'MARACUYA AND CHEESECAKE', category: 'ICE POPS BAÑADOS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 2203, name: 'CHOCOLATE SIN AZUCAR', category: 'ICE POPS BAÑADOS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 2043, name: 'SORBETE SUPREMO 80%', category: 'ICE POPS LUXURY', unit: 'Unidad', avgWeight: null, price1: 1.248, price2: 0.501 },
  { code: 2041, name: 'KING DOBLE CHOCOLATE', category: 'ICE POPS LUXURY', unit: 'Unidad', avgWeight: null, price1: 1.571, price2: 0.524 },
  { code: 2039, name: 'CHOCOLATE Y DOBLE CHOCOLATE', category: 'ICE POPS LUXURY', unit: 'Unidad', avgWeight: null, price1: 1.571, price2: 0.753 },
  { code: 2044, name: 'TONIO COOKIES & CREAM', category: 'ICE POPS LUXURY', unit: 'Unidad', avgWeight: null, price1: 1.46, price2: 0.638 },
  { code: 2053, name: 'MINION', category: 'ICE POPS LUXURY', unit: 'Unidad', avgWeight: null, price1: 1.505, price2: 0.81 },
  { code: 2040, name: 'ENZO DULCE DE LECHE E GIANDUIA', category: 'ICE POPS LUXURY', unit: 'Unidad', avgWeight: null, price1: 1.272, price2: 0.544 },
  { code: 2042, name: 'PISTACCHIO SICILIA', category: 'ICE POPS LUXURY', unit: 'Unidad', avgWeight: null, price1: 1.308, price2: 0.675 },
  { code: 2401, name: 'ICE POP DUBAI', category: 'ICE POP DUBAI', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 2187, name: 'FRASCOS DDL', category: 'FRASCOS DDL', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 2386, name: 'YOGUR DE FRESA', category: 'CANNOLIS', unit: 'Unidad', avgWeight: null, price1: 0.946, price2: 0.946 },
  { code: 2384, name: 'DULCE DE LECHE', category: 'CANNOLIS', unit: 'Unidad', avgWeight: null, price1: 1.05, price2: 1.046 },
  { code: 2388, name: 'DULCE CON COCO', category: 'CANNOLIS', unit: 'Unidad', avgWeight: null, price1: 0.944, price2: 1.05 },
  { code: 2385, name: 'PISTACHO', category: 'CANNOLIS', unit: 'Unidad', avgWeight: null, price1: 0.934, price2: 0.96 },
  { code: 2387, name: 'GIANDUIA', category: 'CANNOLIS', unit: 'Unidad', avgWeight: null, price1: 1.046, price2: 0.934 },
  { code: 2200, name: 'CHEESECAKE', category: 'PASTELERIA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 2201, name: 'PISTACCHIO', category: 'PASTELERIA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 2199, name: 'ROCHER', category: 'PASTELERIA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 2156, name: 'TERMICOS TAKE AWAY 1 KG', category: 'TERMICOS', unit: 'Unidad', avgWeight: null, price1: 1.03, price2: 1.03 },
  { code: 2157, name: 'TERMICOS TAKE AWAY 1/2 KG', category: 'TERMICOS', unit: 'Unidad', avgWeight: null, price1: 0.73, price2: 0.73 },
  { code: 2396, name: 'TERMICOS TAKE AWAY 1/4 KG', category: 'TERMICOS', unit: 'Unidad', avgWeight: null, price1: 0.44, price2: 0.44 },
  { code: 90001, name: 'LATAS ICEPOP DUBAI', category: 'TERMICOS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 2289, name: 'CUCHARITAS PAPEL BLANCO (stenger)', category: 'CUCHARAS', unit: 'Unidad', avgWeight: null, price1: 0.04, price2: 0.04 },
  { code: 2062, name: 'CIALDAS', category: 'CUCURUCHOS', unit: 'Unidad', avgWeight: null, price1: 0.021, price2: 0.021 },
  { code: 2170, name: 'CUCURUCHO GOURMET NOCCIOLA', category: 'CUCURUCHOS', unit: 'Unidad', avgWeight: null, price1: 0.389, price2: 0.389 },
  { code: 2171, name: 'CUCURUCHO GOURMET PISTACCHIO', category: 'CUCURUCHOS', unit: 'Unidad', avgWeight: null, price1: 0.56, price2: 0.56 },
  { code: 2172, name: 'CUCURUCHO GRANDE GOURMET GRANDE', category: 'CUCURUCHOS', unit: 'Unidad', avgWeight: null, price1: 0.88, price2: 0.88 },
  { code: 2380, name: 'CUCURUCHO BIG BLACK PISTACCHIO "XL"', category: 'CUCURUCHOS', unit: 'Unidad', avgWeight: null, price1: 1.17, price2: 1.17 },
  { code: 2173, name: 'CUCURUCHO COMUN S (324)', category: 'CUCURUCHOS', unit: 'Unidad', avgWeight: null, price1: 0.108, price2: 0.108 },
  { code: 2174, name: 'CUCURUCHO COMUN M (360)', category: 'CUCURUCHOS', unit: 'Unidad', avgWeight: null, price1: 0.123, price2: 0.123 },
  { code: 2282, name: 'CUCURUCHO COMUN L (300)', category: 'CUCURUCHOS', unit: 'Unidad', avgWeight: null, price1: 0.137, price2: 0.137 },
  { code: 2076, name: 'ARROLATO BICOLOR - CUBANITO', category: 'CUCURUCHOS', unit: 'Unidad', avgWeight: null, price1: 0.069, price2: 0.069 },
  { code: 2286, name: 'PORTACONO PEQUEÑO (Stenger)', category: 'POLIPAPEL', unit: 'Unidad', avgWeight: null, price1: 0.03, price2: 0.03 },
  { code: 2095, name: 'PORTACONO GRANDE (Proni)', category: 'POLIPAPEL', unit: 'Unidad', avgWeight: null, price1: 0.03, price2: 0.03 },
  { code: 2159, name: 'SORBETE POLIPAPEL (Erreme)', category: 'POLIPAPEL', unit: 'Unidad', avgWeight: null, price1: 0.02, price2: 0.02 },
  { code: 90002, name: 'VASCHETTA GRANDE', category: 'POLIPAPEL', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90003, name: 'VASCHETTA PEQUEÑA', category: 'POLIPAPEL', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90004, name: 'VASCHETTA DESCARTABLE', category: 'POLIPAPEL', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 2160, name: 'DOMOS VASCHETTA GRANDE (Erreme)', category: 'POLIPAPEL', unit: 'Unidad', avgWeight: null, price1: 0.77, price2: 0.77 },
  { code: 2185, name: 'BOLSA PASTELERIA', category: 'POLIPAPEL', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 2161, name: 'BOLSA TAKE AWAY (LOGO BARCELONA)', category: 'POLIPAPEL', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 2192, name: 'COPA CHICA (2250)', category: 'POLIPAPEL', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 2193, name: 'COPA MEDIA (2000)', category: 'POLIPAPEL', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 2194, name: 'COPA GRANDE (1400)', category: 'POLIPAPEL', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 2195, name: 'COPA XL (1260)', category: 'POLIPAPEL', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 2288, name: 'COCA COLA - LATA', category: 'BEBIDAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 2112, name: 'COCA COLA ZERO - LATA', category: 'BEBIDAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90005, name: 'SPRITE - LATA', category: 'BEBIDAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 2129, name: 'S.PEREGRINO 500 - PLASTICO', category: 'BEBIDAS', unit: 'Unidad', avgWeight: null, price1: 0.88, price2: 0.88 },
  { code: 2130, name: 'S.PEREGRINO 500 - VIDRIO', category: 'BEBIDAS', unit: 'Unidad', avgWeight: null, price1: 0.9, price2: 0.9 },
  { code: 2284, name: 'Agua Viladrau 500ml - PLASTICO', category: 'BEBIDAS', unit: 'Unidad', avgWeight: null, price1: 0.26, price2: 0.26 },
  { code: 2088, name: 'VASO MILKSHAKE', category: 'MILK SHAKE', unit: 'Unidad', avgWeight: null, price1: 0.122, price2: 0.122 },
  { code: 2089, name: 'TAPA MILKSHAKE', category: 'MILK SHAKE', unit: 'Unidad', avgWeight: null, price1: 0.026, price2: 0.026 },
  { code: 2295, name: 'VASO 100 ML - CAFÉ - MODELO EXPRESS UNA PARED', category: 'CAFÉ', unit: 'Unidad', avgWeight: null, price1: 0.1, price2: 0.1 },
  { code: 2296, name: 'VASO 230 ML - CAFÉ - MODELO EXPRESS UNA PARED', category: 'CAFÉ', unit: 'Unidad', avgWeight: null, price1: 0.12, price2: 0.12 },
  { code: 2297, name: 'VASO 370 ML - CAFÉ - MODELO EXPRESS UNA PARED', category: 'CAFÉ', unit: 'Unidad', avgWeight: null, price1: 0.15, price2: 0.15 },
  { code: 2099, name: 'TAPA 115 ML CAFÉ', category: 'CAFÉ', unit: 'Unidad', avgWeight: null, price1: 0.023, price2: 0.023 },
  { code: 2100, name: 'TAPA 240 ML - CAFÉ', category: 'CAFÉ', unit: 'Unidad', avgWeight: null, price1: 0.023, price2: 0.023 },
  { code: 2101, name: 'TAPA 370 ML - CAFÉ', category: 'CAFÉ', unit: 'Unidad', avgWeight: null, price1: 0.023, price2: 0.023 },
  { code: 2162, name: 'CAPSULAS LEGGERO', category: 'CAPSULAS CAFÉ', unit: 'Cápsula', avgWeight: null, price1: 0.49, price2: 0.49 },
  { code: 2163, name: 'CAPSULAS INTENSO', category: 'CAPSULAS CAFÉ', unit: 'Cápsula', avgWeight: null, price1: 0.49, price2: 0.49 },
  { code: 2164, name: 'CAPSULAS DESCAFEINATO', category: 'CAPSULAS CAFÉ', unit: 'Cápsula', avgWeight: null, price1: 0.49, price2: 0.49 },
  { code: 2165, name: 'CAPSULAS RISTRETTO', category: 'CAPSULAS CAFÉ', unit: 'Cápsula', avgWeight: null, price1: 0.49, price2: 0.49 },
  { code: 2309, name: 'CAPSULA VAINILLA', category: 'CAPSULAS CAFÉ', unit: 'Cápsula', avgWeight: null, price1: 0.49, price2: 0.49 },
  { code: 2310, name: 'CAPSULA CARAMELO', category: 'CAPSULAS CAFÉ', unit: 'Cápsula', avgWeight: null, price1: 0.49, price2: 0.49 },
  { code: 2188, name: 'AZUCAR PORCION', category: 'CAPSULAS CAFÉ', unit: 'Unidad', avgWeight: null, price1: 0.01, price2: 0.01 },
  { code: 2189, name: 'EDULCORANTE PORCION', category: 'CAPSULAS CAFÉ', unit: 'Unidad', avgWeight: null, price1: 0.02, price2: 0.02 },
  { code: 2169, name: 'PALETINAS - REMOVEDORES', category: 'CAPSULAS CAFÉ', unit: 'Unidad', avgWeight: null, price1: 0.0, price2: 0.0 },
  { code: 2190, name: 'AZUCAR BROWN', category: 'CAPSULAS CAFÉ', unit: 'Unidad', avgWeight: null, price1: 0.0, price2: 0.0 },
  { code: 2175, name: 'SERVILLETAS - I LOVE LUCCIANOS -', category: 'SERVILLETAS', unit: 'Unidad', avgWeight: null, price1: 0.003, price2: 0.003 },
  { code: 90006, name: 'DULCE DE LECHE VETEADO', category: 'DULCE DE LECHES', unit: 'Kg', avgWeight: null, price1: null, price2: null },
  { code: 20099, name: 'DULCE DE LECHE CLÁSICO', category: 'DULCE DE LECHES', unit: 'Kg', avgWeight: null, price1: 4.31, price2: 4.31 },
  { code: 20098, name: 'DULCE DE LECHE HELADERO', category: 'DULCE DE LECHES', unit: 'Kg', avgWeight: null, price1: 4.79, price2: 4.79 },
  { code: 20096, name: 'FRESA CONGELADA', category: 'FRUTAS', unit: 'Kg', avgWeight: null, price1: 6.16, price2: 6.16 },
  { code: 20154, name: 'QUESO MASCARPONE', category: 'LACTEOS', unit: 'Kg', avgWeight: null, price1: 8.6, price2: 8.6 },
  { code: 20171, name: 'YEMA PASTEURIZADA', category: 'LACTEOS', unit: 'Litro', avgWeight: null, price1: 10.62, price2: 10.62 },
  { code: 20230, name: 'NATA 35%', category: 'LACTEOS', unit: 'Litro', avgWeight: null, price1: 3.87, price2: 3.87 },
  { code: 20309, name: 'LECHE ATO - SEMIDESNATADA', category: 'LACTEOS', unit: 'Litro', avgWeight: null, price1: null, price2: null },
  { code: 90007, name: 'NATA ESPRAY', category: 'LACTEOS', unit: 'Litro', avgWeight: null, price1: null, price2: null },
  { code: 20151, name: 'LECHE EN POLVO 26% - 25KG', category: 'LACTEOS', unit: 'Kg', avgWeight: null, price1: 5.226, price2: 5.226 },
  { code: 20368, name: 'QUESO PHILADELPHIA 2KG', category: 'LACTEOS', unit: 'Kg', avgWeight: null, price1: null, price2: null },
  { code: 20234, name: 'ESENCIA DE VAINILLA', category: 'INSUMOS PRODUCCION', unit: 'Litro', avgWeight: null, price1: 3.45, price2: 3.45 },
  { code: 90008, name: 'Edulcorante Liquido', category: 'INSUMOS PRODUCCION', unit: 'Litro', avgWeight: null, price1: null, price2: null },
  { code: 20243, name: 'OREO 440 GR -INGRESADO POR PAQUETE', category: 'INSUMOS PRODUCCION', unit: 'Unidad', avgWeight: null, price1: 3.05, price2: 3.05 },
  { code: 90009, name: 'GRANILLO AZUCAR MULTICOLOR', category: 'INSUMOS PRODUCCION', unit: 'Kg', avgWeight: null, price1: null, price2: null },
  { code: 90010, name: 'VAINILLAS TIRAMISÚ', category: 'INSUMOS PRODUCCION', unit: 'Kg', avgWeight: null, price1: null, price2: null },
  { code: 20032, name: 'AZUCAR BLANCA 25 KG', category: 'INSUMOS PRODUCCION', unit: 'Kg', avgWeight: null, price1: 0.73, price2: 0.73 },
  { code: 20039, name: 'DEXTROSA 25KG', category: 'INSUMOS PRODUCCION', unit: 'Kg', avgWeight: null, price1: 2.22, price2: 2.22 },
  { code: 20153, name: 'MALTODEXTRINA', category: 'INSUMOS PRODUCCION', unit: 'Kg', avgWeight: null, price1: 2.48, price2: 2.48 },
  { code: 20257, name: 'GRANILLO DE CACAHUETE (MANI) TOSTADO', category: 'VARIOS PRODUCCION', unit: 'Kg', avgWeight: null, price1: 6.66, price2: 6.66 },
  { code: 20336, name: 'KINA', category: 'VARIOS PRODUCCION', unit: 'Litro', avgWeight: null, price1: 4.3, price2: 4.3 },
  { code: 20268, name: 'TIA MARIA 700ML - INGRESADO POR BOTELLA', category: 'VARIOS PRODUCCION', unit: 'Unidad', avgWeight: null, price1: 13.97, price2: 13.97 },
  { code: 20113, name: 'GRANELLA DE PISTACCHIO', category: 'VARIOS PRODUCCION', unit: 'Kg', avgWeight: null, price1: 32.4, price2: 32.4 },
  { code: 20035, name: 'Coco rallado (Blau)', category: 'VARIOS PRODUCCION', unit: 'Kg', avgWeight: null, price1: 3.6, price2: 3.6 },
  { code: 20044, name: 'Bensdorp 22/24 SR Cacao en polvo alcalinizado', category: 'BARRY CALLEBAUT', unit: 'Kg', avgWeight: null, price1: 10.79, price2: 10.79 },
  { code: 20050, name: 'Cacao Barry Manteca de cacao 3KG', category: 'BARRY CALLEBAUT', unit: 'Kg', avgWeight: null, price1: 25.27, price2: 25.27 },
  { code: 20251, name: 'Cobertura de chocolate con edulcorante 53.9%', category: 'BARRY CALLEBAUT', unit: 'Kg', avgWeight: null, price1: 6.45, price2: 6.45 },
  { code: 20252, name: 'Cobertura de chocolate con leche 34.1%%', category: 'BARRY CALLEBAUT', unit: 'Kg', avgWeight: null, price1: 7.95, price2: 7.95 },
  { code: 20239, name: 'Kumabo Cobertura de chocolate negro 80.1%', category: 'BARRY CALLEBAUT', unit: 'Kg', avgWeight: null, price1: 8.8, price2: 8.8 },
  { code: 20042, name: 'Cobertura Chocolate negro 70.4%', category: 'BARRY CALLEBAUT', unit: 'Kg', avgWeight: null, price1: 7.9, price2: 7.9 },
  { code: 20043, name: 'Chocolate blanco Easymelt', category: 'BARRY CALLEBAUT', unit: 'Kg', avgWeight: null, price1: 9.63, price2: 9.63 },
  { code: 20178, name: 'Cobertura de chocolate con leche 31.9%', category: 'BARRY CALLEBAUT', unit: 'Kg', avgWeight: null, price1: 10.56, price2: 10.56 },
  { code: 20049, name: 'Dark Cobertura de chocolate (STRACCIATELLA) 56.4%', category: 'BARRY CALLEBAUT', unit: 'Kg', avgWeight: null, price1: 13.41, price2: 13.41 },
  { code: 20045, name: 'SELECT COBERTURA DE CHOCOLATE NEGRO 54.1%', category: 'BARRY CALLEBAUT', unit: 'Kg', avgWeight: null, price1: 10.68, price2: 10.68 },
  { code: 20254, name: 'Chocolate blanco (STRACCIATELLA BLANCA) 38.5%', category: 'BARRY CALLEBAUT', unit: 'Kg', avgWeight: null, price1: 13.57, price2: 13.57 },
  { code: 20393, name: 'Fondente vanini 72%', category: 'ICAM', unit: 'Kg', avgWeight: null, price1: 9.48, price2: 9.48 },
  { code: 20385, name: 'Bianca edelweiss (Chocolate blanco)', category: 'ICAM', unit: 'Kg', avgWeight: null, price1: 8.56, price2: 8.56 },
  { code: 20394, name: 'Mabel fondente 56%', category: 'ICAM', unit: 'Kg', avgWeight: null, price1: null, price2: null },
  { code: 20395, name: 'Prestige Latte 32%', category: 'ICAM', unit: 'Kg', avgWeight: null, price1: 11.15, price2: 11.15 },
  { code: 20396, name: 'Chocolate sin azucar agregada', category: 'ICAM', unit: 'Kg', avgWeight: null, price1: 11.63, price2: 11.63 },
  { code: 20392, name: 'Bagua Nativo Peru (81%)', category: 'ICAM', unit: 'Kg', avgWeight: null, price1: 14.47, price2: 14.47 },
  { code: 20397, name: 'Cacao polvo 22/24', category: 'ICAM', unit: 'Kg', avgWeight: null, price1: 11.58, price2: 11.58 },
  { code: 20238, name: 'Chantilly 60 1KG', category: 'SALSAS Y VARIEGATOS BABBI', unit: 'Kg', avgWeight: null, price1: 10.47, price2: 10.47 },
  { code: 20017, name: 'CIOCCODELIZIA CLASSICA SACCHETTO 500G', category: 'SALSAS Y VARIEGATOS BABBI', unit: 'Kg', avgWeight: null, price1: 11.52, price2: 11.52 },
  { code: 20014, name: 'COBERTURA ARTSTICK PISTACCHIO 1KG', category: 'SALSAS Y VARIEGATOS BABBI', unit: 'Kg', avgWeight: null, price1: 16.19, price2: 16.19 },
  { code: 20018, name: 'GOLOSA PISTACCHO 3KG', category: 'SALSAS Y VARIEGATOS BABBI', unit: 'Kg', avgWeight: null, price1: 18.56, price2: 18.56 },
  { code: 20015, name: 'GRANELLA FINE NOCCIOLA PIEMONTE IGP 2KG', category: 'SALSAS Y VARIEGATOS BABBI', unit: 'Kg', avgWeight: null, price1: 28.57, price2: 28.57 },
  { code: 20016, name: 'NOCCIOLE TRIBOLATE TOSTATE 2KG', category: 'SALSAS Y VARIEGATOS BABBI', unit: 'Kg', avgWeight: null, price1: 25.48, price2: 25.48 },
  { code: 20011, name: 'PASTA BUONISSIMO 3KG', category: 'SALSAS Y VARIEGATOS BABBI', unit: 'Kg', avgWeight: null, price1: 16.51, price2: 16.51 },
  { code: 20260, name: 'PASTA CIOCCOLATO BIANCO 3KG', category: 'SALSAS Y VARIEGATOS BABBI', unit: 'Kg', avgWeight: null, price1: 11.9, price2: 11.9 },
  { code: 20002, name: 'PASTA ZABAIONE ROMA 3KG', category: 'SALSAS Y VARIEGATOS BABBI', unit: 'Kg', avgWeight: null, price1: 12.58, price2: 12.58 },
  { code: 20026, name: 'SELEZIONE FONDENTE 1.8KG', category: 'SALSAS Y VARIEGATOS BABBI', unit: 'Kg', avgWeight: null, price1: 12.38, price2: 12.38 },
  { code: 20213, name: 'TOPPING CARAMELLO X1KG', category: 'SALSAS Y VARIEGATOS BABBI', unit: 'Kg', avgWeight: null, price1: 6.99, price2: 6.99 },
  { code: 20214, name: 'TOPPING FRAGOLA X1KG', category: 'SALSAS Y VARIEGATOS BABBI', unit: 'Kg', avgWeight: null, price1: 7.28, price2: 7.28 },
  { code: 20212, name: 'TOPPING FRUTTI DI BOSCO X1KG', category: 'SALSAS Y VARIEGATOS BABBI', unit: 'Kg', avgWeight: null, price1: 7.28, price2: 7.28 },
  { code: 20010, name: 'VARIEGATO PRALINE 3KG', category: 'SALSAS Y VARIEGATOS BABBI', unit: 'Kg', avgWeight: null, price1: 12.48, price2: 12.48 },
  { code: 20173, name: 'BESAME MUCHO 5Kg', category: 'SALSAS Y VARIEGATOS IRCA', unit: 'Kg', avgWeight: null, price1: 17.51, price2: 17.51 },
  { code: 20175, name: 'JOYCREAM AMORENERO Cu-5KG', category: 'SALSAS Y VARIEGATOS IRCA', unit: 'Kg', avgWeight: null, price1: 10.84, price2: 10.84 },
  { code: 20051, name: 'JOYCREAM DONATELLO Cu-5KG', category: 'SALSAS Y VARIEGATOS IRCA', unit: 'Kg', avgWeight: null, price1: 8.42, price2: 8.42 },
  { code: 20054, name: 'JOYCREAM MILK COCA Cu-5kg', category: 'SALSAS Y VARIEGATOS IRCA', unit: 'Kg', avgWeight: null, price1: 4.94, price2: 4.94 },
  { code: 20177, name: 'JOYCREAM WAFERNUT NOIR Cu-5KG', category: 'SALSAS Y VARIEGATOS IRCA', unit: 'Kg', avgWeight: null, price1: 10.99, price2: 10.99 },
  { code: 20141, name: 'JOYCREAM CROCANTISSIMO Cu-5KG', category: 'SALSAS Y VARIEGATOS IRCA', unit: 'Kg', avgWeight: null, price1: 10.06, price2: 10.06 },
  { code: 20145, name: 'JOYFRUIT FRUTOS DEL BOSQUE Cu-3.5KG', category: 'SALSAS Y VARIEGATOS IRCA', unit: 'Kg', avgWeight: null, price1: 11.04, price2: 11.04 },
  { code: 20052, name: 'JOYGGELATO COCO C -6 X 1 KG', category: 'SALSAS Y VARIEGATOS IRCA', unit: 'Kg', avgWeight: null, price1: 11.67, price2: 11.67 },
  { code: 20148, name: 'JOYPASTE PISTACHO GRAN RESERVA 2.5KG', category: 'SALSAS Y VARIEGATOS IRCA', unit: 'Kg', avgWeight: null, price1: null, price2: null },
  { code: 20147, name: 'JOYPASTE NOCCIOLA ITALIA 4KG', category: 'SALSAS Y VARIEGATOS IRCA', unit: 'Kg', avgWeight: null, price1: 26.07, price2: 26.07 },
  { code: 20271, name: 'LILLY CHEESE-KAESE 1KG', category: 'SALSAS Y VARIEGATOS IRCA', unit: 'Kg', avgWeight: null, price1: 10.12, price2: 10.12 },
  { code: 20121, name: 'LILLY NEUTRO 1KG', category: 'SALSAS Y VARIEGATOS IRCA', unit: 'Kg', avgWeight: null, price1: 8.15, price2: 8.15 },
  { code: 20190, name: 'PASTA GIANDUIA 5KG', category: 'SALSAS Y VARIEGATOS IRCA', unit: 'Kg', avgWeight: null, price1: 21.23, price2: 21.23 },
  { code: 20144, name: 'SPECULOOS 5KG', category: 'SALSAS Y VARIEGATOS IRCA', unit: 'Kg', avgWeight: null, price1: 9.97, price2: 9.97 },
  { code: 20053, name: 'WHITE CHOCOLATE x3KG', category: 'SALSAS Y VARIEGATOS IRCA', unit: 'Kg', avgWeight: null, price1: 11.86, price2: 11.86 },
  { code: 20244, name: 'BASE "G"CREME X0.9KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 12.74, price2: 12.74 },
  { code: 20081, name: 'BASE ELENA X 1.8KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 7.43, price2: 7.43 },
  { code: 20069, name: 'BASE LIMONE 50 X 1 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 13.59, price2: 13.59 },
  { code: 20088, name: 'BASE LUCCIANO\'S DULCE DE LECHE X 1.56 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 9.25, price2: 9.25 },
  { code: 20086, name: 'BASE LUCCIANOS STECCHI FRUTTA GUSTO LIMONE X 2KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 7.59, price2: 7.59 },
  { code: 20087, name: 'BASE LUCCIANO\'S STECCHI LATTE X 2KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 9.0, price2: 9.0 },
  { code: 20355, name: 'BASE LUCCIANO\'S 2KG (Base soave)', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 8.72, price2: 8.72 },
  { code: 20061, name: 'CHEESE CAKE BASE X 1 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 14.25, price2: 14.25 },
  { code: 20195, name: 'COPERTURA STRACCHIATELLA 5.5KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: null, price2: null },
  { code: 20090, name: 'COPERTURA AL GUSTO DI CIOCC FONDETE TIPO "M" 5.5 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 10.53, price2: 10.53 },
  { code: 20070, name: 'COOKIES® LEMON MERINGUE X 5.5 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 12.72, price2: 12.72 },
  { code: 20058, name: 'FIORDIBOSCO X 3KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 13.62, price2: 13.62 },
  { code: 20062, name: 'FIORDIMARACUJA X 3 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 13.65, price2: 13.65 },
  { code: 20083, name: 'FROLLINO COOKIES BLACK MEC3X 1KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 9.88, price2: 9.88 },
  { code: 20055, name: 'GRANFRUTTA FRAGOLA X 5 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 8.85, price2: 8.85 },
  { code: 20076, name: 'GRANFRUTTA MANGO ALPHONSO X 5 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 8.33, price2: 8.33 },
  { code: 20074, name: 'GRANFRUTTA MARACUYA X 5KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 8.33, price2: 8.33 },
  { code: 20056, name: 'GRANFRUTTA PESCA X 5 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 7.77, price2: 7.77 },
  { code: 20084, name: 'INSTACRUMBLE NEUTRO X 2.5 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 13.79, price2: 13.79 },
  { code: 20075, name: 'KIT LIMETTA 8X 0.2 KG PASTA', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 8.2, price2: 8.2 },
  { code: 20248, name: 'KIT LIMETTA 8X 1.1 KG BASE', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 8.2, price2: 8.2 },
  { code: 20247, name: 'KIT LIMETTA 1X 1.5 KG VARIEGATO', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 8.2, price2: 8.2 },
  { code: 20246, name: 'NOCCIOLA PRALITANA CIURI CIURIX 2x0.75 KG GRANELLA', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 22.67, price2: 22.67 },
  { code: 20200, name: 'NOCCIOLA PRALITANA CIURI CIURIX 1x2.5 KG PASTA', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 17.86, price2: 17.86 },
  { code: 20339, name: 'SINFONIA 1x6 KG SALTY CARAMEL CREAM', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 11.88, price2: 11.88 },
  { code: 20340, name: 'SINFONIA 4.2KG PASTA GIANDUIA BIANCA', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 14.58, price2: 14.58 },
  { code: 20341, name: 'SINFONIA 2.5 KG INSTACRUMBLE AL CACAO SALATO GLUTEN F', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 12.95, price2: 12.95 },
  { code: 20089, name: 'MEC FIBRA PLUS x 1,8 Kg', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 11.88, price2: 11.88 },
  { code: 20249, name: 'MECPLUS X2.5', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 15.54, price2: 15.54 },
  { code: 20330, name: 'MORETTINA PEPITA 5.5 Kg', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 12.99, price2: 12.99 },
  { code: 20065, name: 'MISTER NICO PASTA x 4 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 13.86, price2: 13.86 },
  { code: 20066, name: 'MISTER NICO VARIEGATO X 4 KG KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 10.44, price2: 10.44 },
  { code: 20208, name: 'PASTA BANANA CON PEZZI 3KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 10.75, price2: 10.75 },
  { code: 20068, name: 'PASTA BISCOTTINO X 4.5 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 11.85, price2: 11.85 },
  { code: 20381, name: 'PASTA BREZEL CREAM X4,2 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 13.2, price2: 13.2 },
  { code: 20383, name: 'PASTA CREMA CHOCOMILKY X6 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 14.97, price2: 14.97 },
  { code: 20079, name: 'PASTA FRAGOLA ROSSA X 3 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 9.36, price2: 9.36 },
  { code: 20059, name: 'PASTA NOCCIOLA SELECTION X 5KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 20.0, price2: 20.0 },
  { code: 20063, name: 'PASTA PER COOKIES® BLACK X 4,5 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 12.39, price2: 12.39 },
  { code: 20060, name: 'PASTA PISTACCHIO 100% SICILIA C.C.- 4KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 40.39, price2: 40.39 },
  { code: 20188, name: 'PASTA TIRAMISU X 4.5KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 11.5, price2: 11.5 },
  { code: 20328, name: 'PASTA VAINILLA PURA TOP 3,5 Kg', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 18.9, price2: 18.9 },
  { code: 20348, name: 'QUELLA® NOCCIOLA PRALINE 6 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 9.45, price2: 9.45 },
  { code: 20095, name: 'QUELLA® PISTACCHIO X 6 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 17.49, price2: 17.49 },
  { code: 20325, name: 'QUELLA® PISTACCHIO \'G\' X 6 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 17.49, price2: 17.49 },
  { code: 20379, name: 'QUELLA® WHITE X 6 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 7.94, price2: 7.94 },
  { code: 20077, name: 'QUELLA® X 6 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 6.65, price2: 6.65 },
  { code: 20390, name: 'QUELLA® X 23 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: null, price2: null },
  { code: 20067, name: 'QUELLO® X 6 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 7.47, price2: 7.47 },
  { code: 20080, name: 'SOFTIN x 3.5 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 8.75, price2: 8.75 },
  { code: 20082, name: 'SUPERGELMIX x 3 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 10.71, price2: 10.71 },
  { code: 20057, name: 'SWEET GUSTO MASCARPONE X2KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 17.68, price2: 17.68 },
  { code: 20211, name: 'TUTTOPAN C10 X 2.5kg', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 20.71, price2: 20.71 },
  { code: 20210, name: 'YOGHIN X 1KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: null, price2: null },
  { code: 20384, name: 'VARIEGATO DUBAI CHOCOLATE X5.5 KG', category: 'SALSAS Y VARIEGATOS MEC 3', unit: 'Kg', avgWeight: null, price1: 16.34, price2: 15.62 },
  { code: 20334, name: 'PASTA GELSO ROSSO 3.5 KG', category: 'CITTÀ DEL GELATO', unit: 'Kg', avgWeight: null, price1: 8.3, price2: 8.3 },
  { code: 20335, name: 'VARIEGATO GELSO ROSSO 3.5 KG', category: 'CITTÀ DEL GELATO', unit: 'Kg', avgWeight: null, price1: 6.9, price2: 6.9 },
  { code: 20374, name: 'LOVERIA COCCO 5,5 KG', category: 'LEAGEL', unit: 'Kg', avgWeight: null, price1: 11.9, price2: 11.9 },
  { code: 20370, name: 'LOVERIA PISTACCHIO 5,5 KG', category: 'LEAGEL', unit: 'Kg', avgWeight: null, price1: 17.15, price2: 17.15 },
  { code: 20373, name: 'FRUIT PASSION 2KG', category: 'LEAGEL', unit: 'Kg', avgWeight: null, price1: 13.3, price2: 13.3 },
  { code: 20369, name: 'CHEESCAKE 50 2KG', category: 'LEAGEL', unit: 'Kg', avgWeight: null, price1: 18.5, price2: 18.5 },
  { code: 20371, name: 'CRUMBLE PISTACCHIO 2,5 KG', category: 'LEAGEL', unit: 'Kg', avgWeight: null, price1: 17.15, price2: 17.15 },
  { code: 20378, name: 'CIOCCOPISTACCHIO 5KG', category: 'LEAGEL', unit: 'Kg', avgWeight: null, price1: 18.4, price2: 18.4 },
  { code: 20372, name: 'PASTA MANGO ALPHONSO 3,5 KG', category: 'LEAGEL', unit: 'Kg', avgWeight: null, price1: 11.2, price2: 11.2 },
  { code: 90011, name: 'AZUL', category: 'COLORANTES', unit: 'Kg', avgWeight: null, price1: null, price2: null },
  { code: 90012, name: 'ROJO REMOLACHA', category: 'COLORANTES', unit: 'Kg', avgWeight: null, price1: null, price2: null },
  { code: 90013, name: 'ROJO', category: 'COLORANTES', unit: 'Kg', avgWeight: null, price1: null, price2: null },
  { code: 90014, name: 'VERDE', category: 'COLORANTES', unit: 'Kg', avgWeight: null, price1: null, price2: null },
  { code: 90015, name: 'AMARILLO', category: 'COLORANTES', unit: 'Kg', avgWeight: null, price1: null, price2: null },
  { code: 2186, name: 'BANDAS CIERRA POTES', category: 'VARIOS', unit: 'Unidad', avgWeight: null, price1: 0.0, price2: 0.0 },
  { code: 2291, name: 'CAJA PASTELERIA', category: 'VARIOS', unit: 'Unidad', avgWeight: null, price1: 0.42, price2: 0.42 },
  { code: 90016, name: 'VASOS PLASTICO PASTELERIA (POSTRES)', category: 'VARIOS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90017, name: 'ROLLOS TERMICOS CAJA', category: 'VARIOS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90018, name: 'PELUCHES TONIO', category: 'VARIOS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90019, name: 'PELUCHES TONIO BANDA', category: 'VARIOS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90020, name: 'PELUCHES ENZO', category: 'VARIOS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90021, name: 'BOLSA BASURA BLANCA', category: 'ARTICULOS DE LIMPIEZA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90022, name: 'BOLSA BASURA NEGRA', category: 'ARTICULOS DE LIMPIEZA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90023, name: 'GUANTES S (100und.)', category: 'ARTICULOS DE LIMPIEZA', unit: 'Caja', avgWeight: null, price1: null, price2: null },
  { code: 90024, name: 'GUANTES M (100und.)', category: 'ARTICULOS DE LIMPIEZA', unit: 'Caja', avgWeight: null, price1: null, price2: null },
  { code: 90025, name: 'GUANTES L (100und.)', category: 'ARTICULOS DE LIMPIEZA', unit: 'Caja', avgWeight: null, price1: null, price2: null },
  { code: 90026, name: 'PAPEL DE MANOS', category: 'ARTICULOS DE LIMPIEZA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90027, name: 'PAPEL HIGIENICO', category: 'ARTICULOS DE LIMPIEZA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90028, name: 'PRODUCTO WC', category: 'ARTICULOS DE LIMPIEZA', unit: 'Litro', avgWeight: null, price1: null, price2: null },
  { code: 90029, name: 'ECOGRAS (desengrasante)', category: 'ARTICULOS DE LIMPIEZA', unit: 'Litro', avgWeight: null, price1: null, price2: null },
  { code: 90030, name: 'ICE FRESH DESODOR', category: 'ARTICULOS DE LIMPIEZA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90031, name: 'V75 AMBIENTADOR', category: 'ARTICULOS DE LIMPIEZA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90032, name: 'CAJA BAGINBOX', category: 'ARTICULOS DE LIMPIEZA', unit: 'Litro', avgWeight: null, price1: null, price2: null },
  { code: 90033, name: 'HANDGRAS', category: 'ARTICULOS DE LIMPIEZA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90034, name: 'DERMO FOAM (JABON BAÑO CLIENTES)', category: 'ARTICULOS DE LIMPIEZA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90035, name: 'DERMO FOAM (JABON ENPLEADOS)', category: 'ARTICULOS DE LIMPIEZA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90036, name: 'SANIT VIRUGEL (ALCOHOL DE MANOS)', category: 'ARTICULOS DE LIMPIEZA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90037, name: 'VALLETAS AZULES', category: 'ARTICULOS DE LIMPIEZA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90038, name: 'VALLETAS VERDES', category: 'ARTICULOS DE LIMPIEZA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90039, name: 'VALLETAS ROJAS', category: 'ARTICULOS DE LIMPIEZA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90040, name: 'TRAPOS PARA CRISTALES', category: 'ARTICULOS DE LIMPIEZA', unit: 'Kg', avgWeight: null, price1: null, price2: null },
  { code: 90041, name: 'ESPONJAS', category: 'ARTICULOS DE LIMPIEZA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90042, name: 'SANIT IPA', category: 'ARTICULOS DE LIMPIEZA', unit: 'Litro', avgWeight: null, price1: null, price2: null },
  { code: 90043, name: 'FOR LAV', category: 'ARTICULOS DE LIMPIEZA', unit: 'Litro', avgWeight: null, price1: null, price2: null },
  { code: 90044, name: 'VITRO', category: 'ARTICULOS DE LIMPIEZA', unit: 'Litro', avgWeight: null, price1: null, price2: null },
  { code: 90045, name: 'SPEED NATUR', category: 'ARTICULOS DE LIMPIEZA', unit: 'Litro', avgWeight: null, price1: null, price2: null },
  { code: 90046, name: 'FOR CHLOR', category: 'ARTICULOS DE LIMPIEZA', unit: 'Litro', avgWeight: null, price1: null, price2: null },
  { code: 90047, name: 'CABEZA DE MOCHO', category: 'ARTICULOS DE LIMPIEZA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90048, name: 'CABEZAS DE ESCOBA', category: 'ARTICULOS DE LIMPIEZA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90049, name: 'PALOS ESCOBA', category: 'ARTICULOS DE LIMPIEZA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90050, name: 'SACOS DE SAL', category: 'ARTICULOS DE LIMPIEZA', unit: 'Kg', avgWeight: null, price1: null, price2: null },
  { code: 90051, name: 'MOLDE ICEPOP FRUTA', category: 'MOLDES/SELLOS LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90052, name: 'MOLDE ICEPOP CLASSIC', category: 'MOLDES/SELLOS LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90053, name: 'MOLDE ICEPOP CUDRICULADO', category: 'MOLDES/SELLOS LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90054, name: 'MOLDE CARA (FIORE)', category: 'MOLDES/SELLOS LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90055, name: 'MOLDE CORAZON', category: 'MOLDES/SELLOS LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90056, name: 'MOLDE TONIO', category: 'MOLDES/SELLOS LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90057, name: 'MOLDE OJOS MINION (SIMPLE)', category: 'MOLDES/SELLOS LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90058, name: 'MOLDE OJOS MINION (DOBLE)', category: 'MOLDES/SELLOS LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90059, name: 'MOLDE NARIZ TONIO', category: 'MOLDES/SELLOS LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90060, name: 'MOLDE TIRABUZON', category: 'MOLDES/SELLOS LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90061, name: 'SELLO ICEPOP I LOVE LUCCIANOS', category: 'MOLDES/SELLOS LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90062, name: 'SELLO ICEPOP 80% CACAO', category: 'MOLDES/SELLOS LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90063, name: 'SELLO LUXURY LUCCIANOS', category: 'MOLDES/SELLOS LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90064, name: 'SELLO CARAMEL GOLD', category: 'MOLDES/SELLOS LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90065, name: 'SELLO ICEPOP DUBAI', category: 'MOLDES/SELLOS LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90066, name: 'CAMISA MUJER S', category: 'UNIFORMES AZULES DESPACHANTE BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90067, name: 'CAMISA MUJER M', category: 'UNIFORMES AZULES DESPACHANTE BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90068, name: 'CAMISA MUJER L', category: 'UNIFORMES AZULES DESPACHANTE BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90069, name: 'CAMISA MUJER XL', category: 'UNIFORMES AZULES DESPACHANTE BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90070, name: 'CAMISA MUJER XXL', category: 'UNIFORMES AZULES DESPACHANTE BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90071, name: 'CAMISA HOMBRE S', category: 'UNIFORMES AZULES DESPACHANTE BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90072, name: 'CAMISA HOMBRE M', category: 'UNIFORMES AZULES DESPACHANTE BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90073, name: 'CAMISA HOMBRE L', category: 'UNIFORMES AZULES DESPACHANTE BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90074, name: 'CAMISA HOMBRE XL', category: 'UNIFORMES AZULES DESPACHANTE BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90075, name: 'CAMISA HOMBRE XXL', category: 'UNIFORMES AZULES DESPACHANTE BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90076, name: 'PANTALÓN 36', category: 'UNIFORMES AZULES DESPACHANTE BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90077, name: 'PANTALÓN 38', category: 'UNIFORMES AZULES DESPACHANTE BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90078, name: 'PANTALÓN 40', category: 'UNIFORMES AZULES DESPACHANTE BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90079, name: 'PANTALÓN 42', category: 'UNIFORMES AZULES DESPACHANTE BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90080, name: 'PANTALÓN 44', category: 'UNIFORMES AZULES DESPACHANTE BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90081, name: 'PANTALÓN 46', category: 'UNIFORMES AZULES DESPACHANTE BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90082, name: 'PANTALÓN 48', category: 'UNIFORMES AZULES DESPACHANTE BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90083, name: 'GORRA', category: 'UNIFORMES AZULES DESPACHANTE BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90084, name: 'DELANTAL', category: 'UNIFORMES AZULES DESPACHANTE BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90085, name: 'S', category: 'BUZOS AZULES BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90086, name: 'M', category: 'BUZOS AZULES BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90087, name: 'L', category: 'BUZOS AZULES BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90088, name: 'XL', category: 'BUZOS AZULES BARCELONA', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90089, name: 'CAMISA XS', category: 'CAMISAS BLANCAS ENCARGADOS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90090, name: 'CAMISA S', category: 'CAMISAS BLANCAS ENCARGADOS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90091, name: 'CAMISA M', category: 'CAMISAS BLANCAS ENCARGADOS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90092, name: 'CAMISA L', category: 'CAMISAS BLANCAS ENCARGADOS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90093, name: 'CAMISA XL', category: 'CAMISAS BLANCAS ENCARGADOS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90094, name: 'CAMISA XXL', category: 'CAMISAS BLANCAS ENCARGADOS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90095, name: 'CAMISA XS', category: 'UNIFORMES DESPACHANTE FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90096, name: 'CAMISA S', category: 'UNIFORMES DESPACHANTE FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90097, name: 'CAMISA M', category: 'UNIFORMES DESPACHANTE FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90098, name: 'CAMISA L', category: 'UNIFORMES DESPACHANTE FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90099, name: 'CAMISA XL', category: 'UNIFORMES DESPACHANTE FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90100, name: 'CAMISA XXL', category: 'UNIFORMES DESPACHANTE FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90101, name: 'PANTALÓN 36', category: 'UNIFORMES DESPACHANTE FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90102, name: 'PANTALÓN 38', category: 'UNIFORMES DESPACHANTE FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90103, name: 'PANTALÓN 40', category: 'UNIFORMES DESPACHANTE FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90104, name: 'PANTALÓN 42', category: 'UNIFORMES DESPACHANTE FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90105, name: 'PANTALÓN 44', category: 'UNIFORMES DESPACHANTE FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90106, name: 'PANTALÓN 46', category: 'UNIFORMES DESPACHANTE FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90107, name: 'PANTALÓN 48', category: 'UNIFORMES DESPACHANTE FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90108, name: 'BOINA', category: 'UNIFORMES DESPACHANTE FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90109, name: 'PAJARITAS', category: 'UNIFORMES DESPACHANTE FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90110, name: 'DELANTAL', category: 'UNIFORMES DESPACHANTE FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90111, name: 'XS', category: 'BUZOS NEGROS FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90112, name: 'S', category: 'BUZOS NEGROS FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90113, name: 'M', category: 'BUZOS NEGROS FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90114, name: 'L', category: 'BUZOS NEGROS FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90115, name: 'XL', category: 'BUZOS NEGROS FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90116, name: 'XXL', category: 'BUZOS NEGROS FRANQUICIAS', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90117, name: 'CAMISA BLANCA S', category: 'UNIFORMES LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90118, name: 'CAMISA BLANCA M', category: 'UNIFORMES LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90119, name: 'CAMISA BLANCA L', category: 'UNIFORMES LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90120, name: 'CAMISA BLANCA XL', category: 'UNIFORMES LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90121, name: 'CAMISA BLANCA XXL', category: 'UNIFORMES LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90122, name: 'PANTALÓN S', category: 'UNIFORMES LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90123, name: 'PANTALÓN M', category: 'UNIFORMES LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90124, name: 'PANTALÓN L', category: 'UNIFORMES LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90125, name: 'PANTALÓN XL', category: 'UNIFORMES LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90126, name: 'GORRO', category: 'UNIFORMES LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
  { code: 90127, name: 'DELANTAL', category: 'UNIFORMES LABORATORIO', unit: 'Unidad', avgWeight: null, price1: null, price2: null },
];

const CATEGORIES = [
  'HELADO (KG)',
  'ICE POPS CLASSIC',
  'ICE POPS SIN BAÑO',
  'ICE POPS BAÑADOS',
  'ICE POPS LUXURY',
  'ICE POP DUBAI',
  'FRASCOS DDL',
  'CANNOLIS',
  'PASTELERIA',
  'TERMICOS',
  'CUCHARAS',
  'CUCURUCHOS',
  'POLIPAPEL',
  'BEBIDAS',
  'MILK SHAKE',
  'CAFÉ',
  'CAPSULAS CAFÉ',
  'SERVILLETAS',
  'DULCE DE LECHES',
  'FRUTAS',
  'LACTEOS',
  'INSUMOS PRODUCCION',
  'VARIOS PRODUCCION',
  'BARRY CALLEBAUT',
  'ICAM',
  'SALSAS Y VARIEGATOS BABBI',
  'SALSAS Y VARIEGATOS IRCA',
  'SALSAS Y VARIEGATOS MEC 3',
  'CITTÀ DEL GELATO',
  'LEAGEL',
  'COLORANTES',
  'VARIOS',
  'ARTICULOS DE LIMPIEZA',
  'MOLDES/SELLOS LABORATORIO',
  'UNIFORMES AZULES DESPACHANTE BARCELONA',
  'BUZOS AZULES BARCELONA',
  'CAMISAS BLANCAS ENCARGADOS',
  'UNIFORMES DESPACHANTE FRANQUICIAS',
  'BUZOS NEGROS FRANQUICIAS',
  'UNIFORMES LABORATORIO',
];

if (typeof module !== 'undefined') { module.exports = { PRODUCTS, CATEGORIES }; }